from ..connection import db


# Popula a tabela de artistas com dados iniciais
def seed_artistas():
    artistas = [
        (
            "Ana Beatriz Lima",
            "anabeatriz",
            "ana.lima@example.com",
            "111.222.333-44",
            "senha789",
            "ativo",
            "2023-02-15",
            "../static/assets/perfils/beatriz.jpeg",
            "Ceramista premiada com obras em museus internacionais",
        ),
        (
            "Carlos Eduardo Santos",
            "carlosedu",
            "carlos.santos@example.com",
            "222.333.444-55",
            "senha101",
            "ativo",
            "2023-03-10",
            "../static/assets/perfils/carlos.jpg",
            "Mestre em xilogravura nordestina",
        ),
        (
            "Fernanda Oliveira",
            "feoliveira",
            "fernanda.art@example.com",
            "333.444.555-66",
            "senha202",
            "bloqueado",
            "2023-04-05",
            "../static/assets/perfils/fernanda.jpg",
            "Fotógrafa artística com foco em cultura popular",
        ),
        (
            "Ricardo Almeida",
            "ricardoarte",
            "ricardo.a@example.com",
            "444.555.666-77",
            "senha303",
            "ativo",
            "2023-05-20",
            "../static/assets/perfils/ricardo.jpg",
            "Escultor em barro com técnicas ancestrais",
        ),
        (
            "Juliana Costa",
            "jucosta",
            "juliana.c@example.com",
            "555.666.777-88",
            "senha404",
            "ativo",
            "2023-06-12",
            "../static/assets/perfils/juliana.jpg",
            "Ilustradora digital com temas folclóricos",
        ),
        (
            "Marcos Vinícius Rocha",
            "marcosvr",
            "marcos.rocha@example.com",
            "666.777.888-99",
            "senha505",
            "desativado",
            "2023-07-08",
            "../static/assets/perfils/marcos.jpg",
            "Artista têxtil com técnicas de bordado inovadoras",
        ),
        (
            "Patrícia Mendes",
            "patymendes",
            "patricia.m@example.com",
            "777.888.999-00",
            "senha606",
            "ativo",
            "2023-08-25",
            "../static/assets/perfils/patricia.jpg",
            "Criadora de bijuterias artesanais com materiais naturais",
        ),
        (
            "Lucas Gabriel Soares",
            "lucasgsoares",
            "lucas.g@example.com",
            "888.999.000-11",
            "senha707",
            "ativo",
            "2023-09-17",
            "../static/assets/perfils/lucas.jpg",
            "Especialista em cordel e literatura de cordel",
        ),
        (
            "Isabela Martins",
            "isamartins",
            "isabela.m@example.com",
            "999.000.111-22",
            "senha808",
            "ativo",
            "2023-10-05",
            "../static/assets/perfils/isabela.jpg",
            "Artista de arte reciclada com consciência ambiental",
        ),
        (
            "Roberto Ferreira",
            "robertofer",
            "roberto.f@example.com",
            "000.111.222-33",
            "senha909",
            "ativo",
            "2023-11-30",
            "../static/assets/perfils/roberto.jpg",
            "Pintor naïf com reconhecimento internacional",
        ),
        (
            "Tatiane Ribeiro",
            "tatiribeiro",
            "tatiane.r@example.com",
            "123.987.456-00",
            "senha010",
            "ativo",
            "2023-12-12",
            "../static/assets/perfils/tatiane.jpg",
            "Artesã especializada em bonecas de pano regionais",
        ),
        (
            "Antônio Carlos Jobim",
            "jobimarte",
            "jobim.art@example.com",
            "456.789.012-34",
            "senha111",
            "ativo",
            "2024-01-18",
            "../static/assets/perfils/jobim.jpg",
            "Escultor em madeira com influências indígenas",
        ),
        (
            "Helena Souza",
            "helenas",
            "helena.s@example.com",
            "567.890.123-45",
            "senha121",
            "bloqueado",
            "2024-02-22",
            "../static/assets/perfils/helena.jpg",
            "Pintora abstrata com elementos da cultura popular",
        ),
        (
            "Felipe Augusto",
            "felipeaug",
            "felipe.a@example.com",
            "678.901.234-56",
            "senha131",
            "ativo",
            "2024-03-07",
            "../static/assets/perfils/felipe.jpg",
            "Artista digital que mistura técnicas tradicionais",
        ),
        (
            "Camila Ventura",
            "camilaventura",
            "camila.v@example.com",
            "789.012.345-67",
            "senha141",
            "ativo",
            "2024-04-14",
            "../static/assets/perfils/camila.jpg",
            "Ceramista utilitária com designs contemporâneos",
        ),
    ]

    with db.get_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM artistas")
        if cursor.fetchone()[0] == 0:
            cursor.executemany(
                "INSERT INTO artistas (nome_completo, usuario, email, cpf_cnpj, senha, status_artista, data_cadastro, url_avatar, biografia) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                artistas,
            )
            print("Artistas iniciais inseridos com sucesso!")
            conn.commit()
        else:
            print("Artistas já existem no banco, pulando inserção.")
