from ..connection import db


def seed_obras():
    obras = [
        # artista_id, título, descrição, técnica, dimensões, preço, categoria_id, url_foto, status_obras, estoque, ano_criacao, data_cadastro
        (
            1,
            "A",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "AB",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABC",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCD",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCDE",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCDEF",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCDEFG",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCDEFGH",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCDEFGHI",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCDEFGHIJ",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "ABCDEFGHIJL",
            "Vaso de cerâmica com padrões nordestinos.",
            "Cerâmica queimada",
            "25x30cm",
            250.00,
            1,
            "/static/assets/uploads/obras/vaso_memorias.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            1,
            "Vaso das Lembraças",
            "Vaso de barro com padrões nordestinos.",
            "barro queimada",
            "25x30cm",
            250.00,
            2,
            "/static/assets/uploads/obras/vaso_lembracas.jpg",
            "ativa",
            10,
            "2023",
            "2025-06-01",
        ),
        (
            1,
            "goiaba",
            "Vaso de madeira com padrões nordestinos.",
            "madeira queimada",
            "25x30cm",
            250.00,
            4,
            "/static/assets/uploads/obras/vaso_sonhos.jpg",
            "ativa",
            10,
            "2023",
            "2025-06-01",
        ),
        (
            1,
            "xalala",
            "Vaso de argila com padrões nordestinos.",
            "argila queimada",
            "25x30cm",
            250.00,
            5,
            "/static/assets/uploads/obras/vaso_estimulos.jpg",
            "ativa",
            10,
            "2023",
            "2025-06-01",
        ),
        (
            2,
            "Xilogravura Sertaneja",
            "Obra que representa o sertão e suas lutas.",
            "Xilogravura em madeira",
            "50x70cm",
            180.00,
            2,
            "/static/assets/uploads/obras/xilogravura_sertaneja.jpg",
            "ativa",
            5,
            "2023",
            "2025-05-01",
        ),
        (
            3,
            "Cultura em Foco",
            "Fotografia artística de feira popular.",
            "Fotografia digital",
            "40x60cm",
            320.00,
            3,
            "/static/assets/uploads/obras/cultura_foco.jpg",
            "ativa",
            7,
            "2023",
            "2025-05-01",
        ),
        (
            4,
            "Barro Ancestral",
            "Escultura representando ancestralidade afro-brasileira.",
            "Barro cru",
            "20x25x15cm",
            400.00,
            1,
            "/static/assets/uploads/obras/barro_ancestral.jpg",
            "ativa",
            3,
            "2023",
            "2025-05-01",
        ),
        (
            5,
            "Folclore Vivo",
            "Ilustração de entidades do folclore brasileiro.",
            "Ilustração digital",
            "A4",
            150.00,
            3,
            "/static/assets/uploads/obras/folclore_vivo.jpg",
            "ativa",
            20,
            "2023",
            "2025-05-01",
        ),
        (
            6,
            "Bordado do Sertão",
            "Tecido bordado com paisagem sertaneja.",
            "Bordado livre",
            "60x60cm",
            280.00,
            4,
            "/static/assets/uploads/obras/bordado_sertao.jpg",
            "ativa",
            6,
            "2023",
            "2025-05-01",
        ),
        (
            7,
            "Natureza em Fio",
            "Bijuterias inspiradas em elementos da floresta.",
            "Materiais naturais",
            "kit com 5 peças",
            90.00,
            5,
            "/static/assets/uploads/obras/natureza_fio.jpg",
            "ativa",
            15,
            "2023",
            "2025-05-01",
        ),
        (
            8,
            "Cordel Ilustrado",
            "Obra que mistura texto e ilustração de cordel.",
            "Cordel impresso",
            "20 páginas",
            50.00,
            2,
            "/static/assets/uploads/obras/cordel_ilustrado.jpg",
            "ativa",
            25,
            "2023",
            "2025-05-01",
        ),
        (
            9,
            "Recicloarte",
            "Obra feita com materiais reciclados coloridos.",
            "Reciclagem criativa",
            "60x80cm",
            200.00,
            3,
            "/static/assets/uploads/obras/recicloarte.jpg",
            "ativa",
            10,
            "2023",
            "2025-05-01",
        ),
        (
            10,
            "Naïf Tropical",
            "Pintura com cenas de festas populares.",
            "Tinta acrílica",
            "80x100cm",
            600.00,
            1,
            "/static/assets/uploads/obras/naif_tropical.jpg",
            "ativa",
            2,
            "2023",
            "2025-05-01",
        ),
        (
            11,
            "Boneca Maria Bonita",
            "Boneca de pano inspirada no cangaço.",
            "Tecido e linha",
            "30cm",
            75.00,
            4,
            "/static/assets/uploads/obras/boneca_maria.jpg",
            "ativa",
            12,
            "2023",
            "2025-05-01",
        ),
        (
            12,
            "Totem Indígena",
            "Escultura em madeira com símbolos indígenas.",
            "Escultura em madeira",
            "100x20cm",
            480.00,
            1,
            "/static/assets/uploads/obras/totem_indigena.jpg",
            "ativa",
            4,
            "2024",
            "2025-05-01",
        ),
        (
            13,
            "Explosão Abstrata",
            "Pintura abstrata com cores vibrantes.",
            "Óleo sobre tela",
            "100x100cm",
            700.00,
            1,
            "/static/assets/uploads/obras/explosao_abstrata.jpg",
            "ativa",
            3,
            "2024",
            "2025-05-01",
        ),
        (
            14,
            "Mestiçagem Digital",
            "Obra digital com colagens de culturas brasileiras.",
            "Arte digital",
            "A3",
            350.00,
            3,
            "/static/assets/uploads/obras/mesticagem_digital.jpg",
            "ativa",
            5,
            "2024",
            "2025-05-01",
        ),
        (
            15,
            "Panelas Contemporâneas",
            "Peças utilitárias em cerâmica com toque moderno.",
            "Cerâmica vitrificada",
            "diâmetro 20cm",
            220.00,
            1,
            "/static/assets/uploads/obras/panelas_contemporaneas.jpg",
            "ativa",
            8,
            "2024",
            "2025-05-01",
        ),
    ]

    with db.get_conn() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM obras")
        if cursor.fetchone()[0] == 0:
            cursor.executemany(
                """
                INSERT INTO obras (
                    artista_id, titulo, descricao, tecnica, dimensoes, preco,
                    categoria_id, url_foto, status_obras, estoque, ano_criacao, data_cadastro
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                obras,
            )
            conn.commit()
            print("Obras inseridas com sucesso!")
        else:
            print("Obras já existem no banco, pulando inserção.")
