"""Add descricao

Revision ID: ad3265f487cf
Revises: 
Create Date: 2025-05-02 22:48:39.335219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3265f487cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivo', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
